---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  strategy:
    type: Recreate  # PVCを使用するため、Recreateストラテジーを使用
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        runAsUser: 1000  # 非rootユーザーで実行
        runAsGroup: 1000
        fsGroup: 1000  # ボリュームの所有権を設定
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        ports:
        - name: http
          containerPort: 8096
          protocol: TCP
        - name: https
          containerPort: 8920
          protocol: TCP
        env:
        - name: TZ
          value: "Asia/Tokyo"  # タイムゾーンを設定
        securityContext:
          allowPrivilegeEscalation: false  # 権限昇格を禁止
          readOnlyRootFilesystem: true  # ルートファイルシステムを読み取り専用に
          runAsNonRoot: true  # 非rootユーザーとして実行を強制
          capabilities:
            drop:
            - ALL  # すべてのLinux capabilitiesを削除
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
          readOnly: true  # メディアディレクトリは読み取り専用
        - name: cache
          mountPath: /cache  # Jellyfinがキャッシュを書き込むための場所
        - name: tmp
          mountPath: /tmp  # 一時ファイル用
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config  # 設定ファイルはPVCでOK
      - name: media
        hostPath:
          path: /mnt/raid/media  # Sambaで共有しているパス
          type: Directory  # ディレクトリが存在することを確認（DirectoryOrCreateは間違ったディレクトリを作成してしまう可能性がある）
      - name: cache
        emptyDir: {}  # Podごとに一時的なキャッシュディレクトリ
      - name: tmp
        emptyDir: {}  # 一時ファイル用ディレクトリ
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  type: NodePort  # Ingressを使用する場合はClusterIP、直接アクセスする場合はLoadBalancerまたはNodePort
  ports:
  - name: http
    port: 8096
    targetPort: http
    nodePort: 30096  # 追加：固定ポート指定
    protocol: TCP
  - name: https
    port: 8920
    targetPort: https
    protocol: TCP
  selector:
    app: jellyfin
